export default [
  {code: 0, cause: '登录后将自动启动加速'},
  {code: 1, cause: '用户登录（WEB、APP）'},
  {code: 2, cause: '异常恢复登录'},
  {code: 3, cause: '用户登出（WEB、APP）'},
  {code: 4, cause: '多设备登录时强制登出'},
  {code: 5, cause: '用户启动加速'},
  {code: 6, cause: '断电重启或者Qeeyoud挂掉重启时恢复加速状态'},
  {code: 7, cause: 'WAN口网络恢复启动加速'},
  {code: 8, cause: '用户停止加速'},
  {code: 9, cause: '加速进程通知加速成功'},
  {code: 10, cause: 'WAN口中断通知加速断开'},
  {code: 11, cause: '加速进程通知加速断开'},
  {code: 12, cause: '加速通知超时检测到加速失败(加速进程启动成功，但是隧道未建立成功)'},
  {code: 13, cause: '加速通知超时检测到加速成功'},
  {code: 14, cause: '强制其它设备设备断开加速通道'},
  {code: 15, cause: '节点网络错误，请切换节点'},
  {code: 16, cause: '启动加速失败(加速进程启动失败)'},
  {code: 17, cause: '账号过期导致加速停止'}
]
